use sha2::{Digest, Sha256};
use std::env;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use wesley_core::{TypeKind, TypeReference, WesleyIR};

const GENERATOR_ID: &str = "bunny-wesley/0.1.0";
const WESLEY_CORE_VERSION: &str = "0.0.5";

#[derive(Debug)]
struct Config {
    schema: PathBuf,
    rust: PathBuf,
    typescript: PathBuf,
    manifest: PathBuf,
}

fn main() {
    if let Err(error) = run() {
        eprintln!("bunny-wesley: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), Box<dyn Error>> {
    let config = parse_args(env::args().skip(1))?;
    let schema_source = fs::read_to_string(&config.schema)?;
    let schema_ir = wesley_core::lower_schema_sdl(&schema_source)?;

    let mut hasher = Sha256::new();
    hasher.update(schema_source.as_bytes());
    let schema_hash = format!("{:x}", hasher.finalize());

    write_file(
        &config.rust,
        &render_rust(&schema_ir, &schema_hash, &config.schema),
    )?;
    write_file(
        &config.typescript,
        &render_typescript(&schema_ir, &schema_hash, &config.schema),
    )?;
    write_file(&config.manifest, &render_manifest(&config, &schema_hash))?;

    Ok(())
}

fn parse_args(args: impl Iterator<Item = String>) -> Result<Config, Box<dyn Error>> {
    let mut schema = None;
    let mut rust = None;
    let mut typescript = None;
    let mut manifest = None;
    let mut pending_flag = None::<String>;

    for arg in args {
        if let Some(flag) = pending_flag.take() {
            match flag.as_str() {
                "--rust" => rust = Some(PathBuf::from(arg)),
                "--typescript" => typescript = Some(PathBuf::from(arg)),
                "--manifest" => manifest = Some(PathBuf::from(arg)),
                _ => return Err(format!("unknown flag {flag}").into()),
            }
            continue;
        }

        match arg.as_str() {
            "--rust" | "--typescript" | "--manifest" => pending_flag = Some(arg),
            "--help" | "-h" => return Err(usage().into()),
            value if value.starts_with('-') => {
                return Err(format!("unknown flag {value}\n{}", usage()).into());
            }
            value => {
                if schema.replace(PathBuf::from(value)).is_some() {
                    return Err(format!("multiple schema paths supplied\n{}", usage()).into());
                }
            }
        }
    }

    if let Some(flag) = pending_flag {
        return Err(format!("missing value for {flag}").into());
    }

    Ok(Config {
        schema: schema.ok_or_else(usage)?,
        rust: rust.ok_or_else(usage)?,
        typescript: typescript.ok_or_else(usage)?,
        manifest: manifest.ok_or_else(usage)?,
    })
}

fn usage() -> String {
    "usage: bunny-wesley <schema.graphql> --rust <path> --typescript <path> --manifest <path>"
        .to_string()
}

fn render_rust(schema: &WesleyIR, schema_hash: &str, schema_path: &Path) -> String {
    let mut output = String::new();
    output.push_str("// @generated by bunny-wesley. Do not edit by hand.\n");
    output.push_str(&format!("// source: {}\n\n", schema_path.display()));
    output.push_str("pub const BUNNY_GRAPHICS_SCHEMA_SHA256: &str =\n");
    output.push_str(&format!("    \"{schema_hash}\";\n\n"));
    output.push_str(&format!(
        "pub const BUNNY_WESLEY_GENERATOR: &str = \"{GENERATOR_ID}\";\n"
    ));
    output.push_str(&format!(
        "pub const BUNNY_WESLEY_CORE_VERSION: &str = \"{WESLEY_CORE_VERSION}\";\n\n"
    ));

    for scalar in schema.types.iter().filter(|type_definition| {
        matches!(type_definition.kind, TypeKind::Scalar) && is_bunny_type(&type_definition.name)
    }) {
        if scalar.name.contains('_') {
            output.push_str("#[allow(non_camel_case_types)]\n");
        }
        output.push_str(&format!(
            "pub type {} = {};\n",
            scalar.name,
            rust_scalar_type(&scalar.name)
        ));
    }
    if schema
        .types
        .iter()
        .any(|type_definition| matches!(type_definition.kind, TypeKind::Scalar))
    {
        output.push('\n');
    }

    let objects: Vec<_> = schema
        .types
        .iter()
        .filter(|type_definition| {
            matches!(type_definition.kind, TypeKind::Object) && is_bunny_type(&type_definition.name)
        })
        .collect();

    for (index, object) in objects.iter().enumerate() {
        output.push_str("#[derive(Clone, Debug, PartialEq)]\n");
        output.push_str(&format!("pub struct {} {{\n", object.name));
        for field in &object.fields {
            output.push_str(&format!(
                "    pub {}: {},\n",
                field.name,
                rust_type(&field.r#type)
            ));
        }
        output.push_str("}\n");
        if index + 1 < objects.len() {
            output.push('\n');
        }
    }

    output
}

fn render_typescript(schema: &WesleyIR, schema_hash: &str, schema_path: &Path) -> String {
    let mut output = String::new();
    output.push_str("// @generated by bunny-wesley. Do not edit by hand.\n");
    output.push_str(&format!("// source: {}\n\n", schema_path.display()));
    output.push_str(&format!(
        "export const BUNNY_GRAPHICS_SCHEMA_SHA256 = \"{schema_hash}\" as const;\n\n"
    ));
    output.push_str(&format!(
        "export const BUNNY_WESLEY_GENERATOR = \"{GENERATOR_ID}\" as const;\n"
    ));
    output.push_str(&format!(
        "export const BUNNY_WESLEY_CORE_VERSION = \"{WESLEY_CORE_VERSION}\" as const;\n\n"
    ));

    for scalar in schema.types.iter().filter(|type_definition| {
        matches!(type_definition.kind, TypeKind::Scalar) && is_bunny_type(&type_definition.name)
    }) {
        output.push_str(&format!(
            "export type {} = {};\n",
            scalar.name,
            ts_scalar_type(&scalar.name)
        ));
    }
    if schema
        .types
        .iter()
        .any(|type_definition| matches!(type_definition.kind, TypeKind::Scalar))
    {
        output.push('\n');
    }

    for object in schema.types.iter().filter(|type_definition| {
        matches!(type_definition.kind, TypeKind::Object) && is_bunny_type(&type_definition.name)
    }) {
        output.push_str(&format!("export interface {} {{\n", object.name));
        for field in &object.fields {
            output.push_str(&format!(
                "  readonly {}: {};\n",
                field.name,
                ts_type(&field.r#type)
            ));
        }
        output.push_str("}\n\n");
    }

    output
}

fn render_manifest(config: &Config, schema_sha256: &str) -> String {
    format!(
        concat!(
            "{{\n",
            "  \"generator\": \"{}\",\n",
            "  \"wesleyCore\": \"{}\",\n",
            "  \"schema\": \"{}\",\n",
            "  \"schemaSha256\": \"{}\",\n",
            "  \"outputs\": [\n",
            "    \"{}\",\n",
            "    \"{}\"\n",
            "  ]\n",
            "}}\n"
        ),
        GENERATOR_ID,
        WESLEY_CORE_VERSION,
        json_escape(&config.schema.display().to_string()),
        schema_sha256,
        json_escape(&config.rust.display().to_string()),
        json_escape(&config.typescript.display().to_string())
    )
}

fn rust_type(type_reference: &TypeReference) -> String {
    let named = rust_scalar_or_named_type(&type_reference.base);
    let rendered = if type_reference.is_list || !type_reference.list_wrappers.is_empty() {
        let item = if type_reference.list_item_nullable.unwrap_or(false) {
            format!("Option<{named}>")
        } else {
            named
        };
        format!("Vec<{item}>")
    } else {
        named
    };

    if type_reference.nullable {
        format!("Option<{rendered}>")
    } else {
        rendered
    }
}

fn ts_type(type_reference: &TypeReference) -> String {
    let named = ts_scalar_or_named_type(&type_reference.base);
    let rendered = if type_reference.is_list || !type_reference.list_wrappers.is_empty() {
        let item = if type_reference.list_item_nullable.unwrap_or(false) {
            format!("{} | null", ts_wrap_union(named))
        } else {
            named
        };
        format!("{}[]", ts_wrap_union(item))
    } else {
        named
    };

    if type_reference.nullable {
        format!("{} | null", ts_wrap_union(rendered))
    } else {
        rendered
    }
}

fn rust_scalar_or_named_type(name: &str) -> String {
    match name {
        "String" | "ID" => "String".to_string(),
        "Int" => "i32".to_string(),
        "Float" => "f64".to_string(),
        "Boolean" => "bool".to_string(),
        "BunnyScalar" => "BunnyScalar".to_string(),
        "BunnyFixedQ32_32Raw" => "BunnyFixedQ32_32Raw".to_string(),
        other => other.to_string(),
    }
}

fn rust_scalar_type(name: &str) -> &'static str {
    match name {
        "BunnyScalar" => "f32",
        "BunnyFixedQ32_32Raw" => "i64",
        _ => "String",
    }
}

fn ts_scalar_or_named_type(name: &str) -> String {
    match name {
        "String" | "ID" => "string".to_string(),
        "Int" | "Float" => "number".to_string(),
        "Boolean" => "boolean".to_string(),
        "BunnyScalar" => "BunnyScalar".to_string(),
        "BunnyFixedQ32_32Raw" => "BunnyFixedQ32_32Raw".to_string(),
        other => other.to_string(),
    }
}

fn ts_scalar_type(name: &str) -> &'static str {
    match name {
        "BunnyScalar" => "number",
        "BunnyFixedQ32_32Raw" => "bigint",
        _ => "unknown",
    }
}

fn is_bunny_type(name: &str) -> bool {
    name.starts_with("Bunny")
}

fn ts_wrap_union(rendered_type: String) -> String {
    if rendered_type.contains(" | ") {
        format!("({rendered_type})")
    } else {
        rendered_type
    }
}

fn write_file(path: &Path, content: &str) -> Result<(), Box<dyn Error>> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

fn json_escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_nullable_scalar_and_non_null_list() {
        let nullable_scalar = TypeReference {
            base: "BunnyScalar".to_string(),
            nullable: true,
            is_list: false,
            list_item_nullable: None,
            list_wrappers: Vec::new(),
            leaf_nullable: None,
        };
        let point_list = TypeReference {
            base: "BunnyContactPoint3".to_string(),
            nullable: false,
            is_list: true,
            list_item_nullable: Some(false),
            list_wrappers: Vec::new(),
            leaf_nullable: None,
        };

        assert_eq!(rust_type(&nullable_scalar), "Option<BunnyScalar>");
        assert_eq!(ts_type(&nullable_scalar), "BunnyScalar | null");
        assert_eq!(rust_type(&point_list), "Vec<BunnyContactPoint3>");
        assert_eq!(ts_type(&point_list), "BunnyContactPoint3[]");
    }

    #[test]
    fn preserves_schema_object_order() {
        let schema = r#"
type First {
  value: String!
}

type Second {
  value: Int
}
"#;

        let objects = wesley_core::lower_schema_sdl(schema)
            .expect("schema parses")
            .types;

        assert_eq!(objects[0].name, "First");
        assert_eq!(objects[1].name, "Second");
        assert_eq!(rust_type(&objects[1].fields[0].r#type), "Option<i32>");
    }
}
