use graphql_parser::schema::{
    parse_schema, Definition, Field, ObjectType, ScalarType, Type, TypeDefinition,
};
use sha2::{Digest, Sha256};
use std::env;
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATOR_ID: &str = "bunny-wesley/0";

#[derive(Debug)]
struct Config {
    schema: PathBuf,
    rust: PathBuf,
    typescript: PathBuf,
    manifest: PathBuf,
}

#[derive(Debug)]
struct SchemaShape {
    scalars: Vec<ScalarShape>,
    objects: Vec<ObjectShape>,
}

#[derive(Clone, Debug)]
struct ScalarShape {
    name: String,
}

#[derive(Clone, Debug)]
struct ObjectShape {
    name: String,
    fields: Vec<FieldShape>,
}

#[derive(Clone, Debug)]
struct FieldShape {
    name: String,
    field_type: FieldType,
}

#[derive(Clone, Debug)]
enum FieldType {
    Named(String),
    List(Box<FieldType>),
    NonNull(Box<FieldType>),
}

fn main() {
    if let Err(error) = run() {
        eprintln!("bunny-wesley: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), Box<dyn Error>> {
    let config = parse_args(env::args().skip(1))?;
    let schema_source = fs::read_to_string(&config.schema)?;
    let schema_sha256 = sha256_hex(schema_source.as_bytes());
    let schema = parse_schema_shape(&schema_source)?;

    write_file(
        &config.rust,
        &render_rust(&schema, &schema_sha256, &config.schema),
    )?;
    write_file(
        &config.typescript,
        &render_typescript(&schema, &schema_sha256, &config.schema),
    )?;
    write_file(&config.manifest, &render_manifest(&config, &schema_sha256))?;

    Ok(())
}

fn parse_args(args: impl Iterator<Item = String>) -> Result<Config, Box<dyn Error>> {
    let mut schema = None;
    let mut rust = None;
    let mut typescript = None;
    let mut manifest = None;
    let mut pending_flag = None::<String>;

    for arg in args {
        if let Some(flag) = pending_flag.take() {
            match flag.as_str() {
                "--rust" => rust = Some(PathBuf::from(arg)),
                "--typescript" => typescript = Some(PathBuf::from(arg)),
                "--manifest" => manifest = Some(PathBuf::from(arg)),
                _ => return Err(format!("unknown flag {flag}").into()),
            }
            continue;
        }

        match arg.as_str() {
            "--rust" | "--typescript" | "--manifest" => pending_flag = Some(arg),
            "--help" | "-h" => return Err(usage().into()),
            value if value.starts_with('-') => {
                return Err(format!("unknown flag {value}\n{}", usage()).into());
            }
            value => {
                if schema.replace(PathBuf::from(value)).is_some() {
                    return Err(format!("multiple schema paths supplied\n{}", usage()).into());
                }
            }
        }
    }

    if let Some(flag) = pending_flag {
        return Err(format!("missing value for {flag}").into());
    }

    Ok(Config {
        schema: schema.ok_or_else(usage)?,
        rust: rust.ok_or_else(usage)?,
        typescript: typescript.ok_or_else(usage)?,
        manifest: manifest.ok_or_else(usage)?,
    })
}

fn usage() -> String {
    "usage: bunny-wesley <schema.graphql> --rust <path> --typescript <path> --manifest <path>"
        .to_string()
}

fn parse_schema_shape(schema_source: &str) -> Result<SchemaShape, Box<dyn Error>> {
    let document = parse_schema::<String>(schema_source)?;
    let mut scalars = Vec::new();
    let mut objects = Vec::new();

    for definition in document.definitions {
        if let Definition::TypeDefinition(type_definition) = definition {
            match type_definition {
                TypeDefinition::Scalar(scalar) => scalars.push(convert_scalar(scalar)),
                TypeDefinition::Object(object) => objects.push(convert_object(object)),
                _ => {}
            }
        }
    }

    if objects.is_empty() {
        return Err("schema did not define any object types".into());
    }

    Ok(SchemaShape { scalars, objects })
}

fn convert_scalar(scalar: ScalarType<'_, String>) -> ScalarShape {
    ScalarShape { name: scalar.name }
}

fn convert_object(object: ObjectType<'_, String>) -> ObjectShape {
    ObjectShape {
        name: object.name,
        fields: object.fields.into_iter().map(convert_field).collect(),
    }
}

fn convert_field(field: Field<'_, String>) -> FieldShape {
    FieldShape {
        name: field.name,
        field_type: convert_type(field.field_type),
    }
}

fn convert_type(field_type: Type<'_, String>) -> FieldType {
    match field_type {
        Type::NamedType(name) => FieldType::Named(name),
        Type::ListType(inner) => FieldType::List(Box::new(convert_type(*inner))),
        Type::NonNullType(inner) => FieldType::NonNull(Box::new(convert_type(*inner))),
    }
}

fn render_rust(schema: &SchemaShape, schema_sha256: &str, schema_path: &Path) -> String {
    let mut output = String::new();
    output.push_str("// @generated by bunny-wesley. Do not edit by hand.\n");
    output.push_str(&format!("// source: {}\n\n", schema_path.display()));
    output.push_str("pub const BUNNY_GRAPHICS_SCHEMA_SHA256: &str =\n");
    output.push_str(&format!("    \"{schema_sha256}\";\n\n"));

    for scalar in &schema.scalars {
        if scalar.name.contains('_') {
            output.push_str("#[allow(non_camel_case_types)]\n");
        }
        output.push_str(&format!(
            "pub type {} = {};\n",
            scalar.name,
            rust_scalar_type(&scalar.name)
        ));
    }
    if !schema.scalars.is_empty() {
        output.push('\n');
    }

    for (index, object) in schema.objects.iter().enumerate() {
        output.push_str("#[derive(Clone, Debug, PartialEq)]\n");
        output.push_str(&format!("pub struct {} {{\n", object.name));
        for field in &object.fields {
            output.push_str(&format!(
                "    pub {}: {},\n",
                field.name,
                rust_type(&field.field_type)
            ));
        }
        output.push_str("}\n");
        if index + 1 < schema.objects.len() {
            output.push('\n');
        }
    }

    output
}

fn render_typescript(schema: &SchemaShape, schema_sha256: &str, schema_path: &Path) -> String {
    let mut output = String::new();
    output.push_str("// @generated by bunny-wesley. Do not edit by hand.\n");
    output.push_str(&format!("// source: {}\n\n", schema_path.display()));
    output.push_str(&format!(
        "export const BUNNY_GRAPHICS_SCHEMA_SHA256 = \"{schema_sha256}\" as const;\n\n"
    ));

    for scalar in &schema.scalars {
        output.push_str(&format!(
            "export type {} = {};\n",
            scalar.name,
            ts_scalar_type(&scalar.name)
        ));
    }
    if !schema.scalars.is_empty() {
        output.push('\n');
    }

    for object in &schema.objects {
        output.push_str(&format!("export interface {} {{\n", object.name));
        for field in &object.fields {
            output.push_str(&format!(
                "  readonly {}: {};\n",
                field.name,
                ts_type(&field.field_type)
            ));
        }
        output.push_str("}\n\n");
    }

    output
}

fn render_manifest(config: &Config, schema_sha256: &str) -> String {
    format!(
        concat!(
            "{{\n",
            "  \"generator\": \"{}\",\n",
            "  \"schema\": \"{}\",\n",
            "  \"schemaSha256\": \"{}\",\n",
            "  \"outputs\": [\n",
            "    \"{}\",\n",
            "    \"{}\"\n",
            "  ]\n",
            "}}\n"
        ),
        GENERATOR_ID,
        json_escape(&config.schema.display().to_string()),
        schema_sha256,
        json_escape(&config.rust.display().to_string()),
        json_escape(&config.typescript.display().to_string())
    )
}

fn rust_type(field_type: &FieldType) -> String {
    match field_type {
        FieldType::NonNull(inner) => rust_non_null_type(inner),
        nullable => format!("Option<{}>", rust_non_null_type(nullable)),
    }
}

fn rust_non_null_type(field_type: &FieldType) -> String {
    match field_type {
        FieldType::Named(name) => match name.as_str() {
            "String" | "ID" => "String".to_string(),
            "Int" => "i32".to_string(),
            "Float" => "f64".to_string(),
            "Boolean" => "bool".to_string(),
            other => rust_scalar_or_named_type(other),
        },
        FieldType::List(inner) => format!("Vec<{}>", rust_type(inner)),
        FieldType::NonNull(inner) => rust_non_null_type(inner),
    }
}

fn ts_type(field_type: &FieldType) -> String {
    match field_type {
        FieldType::NonNull(inner) => ts_non_null_type(inner),
        nullable => format!("{} | null", ts_wrap_union(ts_non_null_type(nullable))),
    }
}

fn ts_non_null_type(field_type: &FieldType) -> String {
    match field_type {
        FieldType::Named(name) => match name.as_str() {
            "String" | "ID" => "string".to_string(),
            "Int" | "Float" => "number".to_string(),
            "Boolean" => "boolean".to_string(),
            other => ts_scalar_or_named_type(other),
        },
        FieldType::List(inner) => format!("{}[]", ts_wrap_union(ts_type(inner))),
        FieldType::NonNull(inner) => ts_non_null_type(inner),
    }
}

fn rust_scalar_or_named_type(name: &str) -> String {
    match name {
        "BunnyScalar" => "BunnyScalar".to_string(),
        "BunnyFixedQ32_32Raw" => "BunnyFixedQ32_32Raw".to_string(),
        other => other.to_string(),
    }
}

fn rust_scalar_type(name: &str) -> &'static str {
    match name {
        "BunnyScalar" => "f32",
        "BunnyFixedQ32_32Raw" => "i64",
        _ => "String",
    }
}

fn ts_scalar_or_named_type(name: &str) -> String {
    match name {
        "BunnyScalar" => "BunnyScalar".to_string(),
        "BunnyFixedQ32_32Raw" => "BunnyFixedQ32_32Raw".to_string(),
        other => other.to_string(),
    }
}

fn ts_scalar_type(name: &str) -> &'static str {
    match name {
        "BunnyScalar" => "number",
        "BunnyFixedQ32_32Raw" => "bigint",
        _ => "unknown",
    }
}

fn ts_wrap_union(rendered_type: String) -> String {
    if rendered_type.contains(" | ") {
        format!("({rendered_type})")
    } else {
        rendered_type
    }
}

fn write_file(path: &Path, content: &str) -> Result<(), Box<dyn Error>> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(())
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut output = String::with_capacity(digest.len() * 2);
    for byte in digest {
        output.push_str(&format!("{byte:02x}"));
    }
    output
}

fn json_escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_nullable_scalar_and_non_null_list() {
        let nullable_scalar = FieldType::Named("BunnyScalar".to_string());
        let point_list = FieldType::NonNull(Box::new(FieldType::List(Box::new(
            FieldType::NonNull(Box::new(FieldType::Named("BunnyContactPoint3".to_string()))),
        ))));

        assert_eq!(rust_type(&nullable_scalar), "Option<BunnyScalar>");
        assert_eq!(ts_type(&nullable_scalar), "BunnyScalar | null");
        assert_eq!(rust_type(&point_list), "Vec<BunnyContactPoint3>");
        assert_eq!(ts_type(&point_list), "BunnyContactPoint3[]");
    }

    #[test]
    fn preserves_schema_object_order() {
        let schema = r#"
type First {
  value: String!
}

type Second {
  value: Int
}
"#;

        let objects = parse_schema_shape(schema).expect("schema parses").objects;

        assert_eq!(objects[0].name, "First");
        assert_eq!(objects[1].name, "Second");
        assert_eq!(rust_type(&objects[1].fields[0].field_type), "Option<i32>");
    }
}
