use std::fmt::{self, Write as _};
use std::path::Path;

use wesley_core::{TypeDefinition, TypeKind, TypeReference, WesleyIR};

use crate::profile;

pub(super) const GENERATOR_ID: &str = concat!("bunny-wesley/", env!("CARGO_PKG_VERSION"));
pub(super) const WESLEY_CORE_VERSION: &str = env!("WESLEY_CORE_VERSION");

const BUNNY_TYPE_PREFIX: &str = "Bunny";

fn normalize_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn push_fmt(output: &mut String, args: fmt::Arguments<'_>) {
    output.write_fmt(args).expect("writing to String cannot fail");
}

pub(super) fn render_rust(
    schema: &WesleyIR,
    schema_hash: &str,
    schema_path: &Path,
) -> Result<String, Box<dyn std::error::Error>> {
    let mut output = String::new();
    push_rust_header(&mut output, schema_hash, schema_path);
    push_rust_scalars(&mut output, schema)?;
    profile::push_rust_scalar_profiles(&mut output, schema)?;
    push_rust_objects(&mut output, schema);
    Ok(output)
}

fn push_rust_header(output: &mut String, schema_hash: &str, schema_path: &Path) {
    output.push_str("// @generated by bunny-wesley. Do not edit by hand.\n");
    push_fmt(output, format_args!("// source: {}\n\n", normalize_path(schema_path)));
    output.push_str("/// SHA-256 hash of the source Bunny graphics schema.\n");
    output.push_str("pub const BUNNY_GRAPHICS_SCHEMA_SHA256: &str =\n");
    push_fmt(output, format_args!("    \"{schema_hash}\";\n\n"));
    output.push_str("/// Identifier of the Bunny Wesley generator used for this output.\n");
    push_fmt(
        output,
        format_args!("pub const BUNNY_WESLEY_GENERATOR: &str = \"{GENERATOR_ID}\";\n"),
    );
    output.push_str("/// Version of `wesley-core` used for schema lowering.\n");
    push_fmt(
        output,
        format_args!("pub const BUNNY_WESLEY_CORE_VERSION: &str = \"{WESLEY_CORE_VERSION}\";\n\n"),
    );
}

fn push_rust_scalars(
    output: &mut String,
    schema: &WesleyIR,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut wrote_scalar = false;
    let mut scalars = schema
        .types
        .iter()
        .filter(|type_definition| matches!(type_definition.kind, TypeKind::Scalar))
        .collect::<Vec<_>>();
    scalars.sort_by(|left, right| left.name.cmp(&right.name));
    for scalar in scalars {
        wrote_scalar = true;
        push_rust_scalar(output, scalar)?;
    }
    if wrote_scalar {
        output.push('\n');
    }
    Ok(())
}

fn push_rust_scalar(
    output: &mut String,
    scalar: &TypeDefinition,
) -> Result<(), Box<dyn std::error::Error>> {
    push_fmt(output, format_args!("/// Rust representation for the `{}` scalar.\n", scalar.name));
    if scalar.name.contains('_') {
        output.push_str("#[allow(non_camel_case_types)]\n");
    }
    push_fmt(
        output,
        format_args!("pub type {} = {};\n", scalar.name, profile::rust_scalar_type(scalar)?),
    );
    Ok(())
}

fn push_rust_objects(output: &mut String, schema: &WesleyIR) {
    let mut objects = schema
        .types
        .iter()
        .filter(|type_definition| {
            matches!(type_definition.kind, TypeKind::Object) && is_bunny_type(&type_definition.name)
        })
        .collect::<Vec<_>>();
    objects.sort_by(|left, right| left.name.cmp(&right.name));

    for (index, object) in objects.iter().enumerate() {
        push_rust_object(output, object);
        if index + 1 < objects.len() {
            output.push('\n');
        }
    }
}

fn push_rust_object(output: &mut String, object: &TypeDefinition) {
    push_fmt(output, format_args!("/// Generated DTO for the `{}` schema object.\n", object.name));
    output.push_str("#[derive(Clone, Debug, PartialEq)]\n");
    push_fmt(output, format_args!("pub struct {} {{\n", object.name));
    for field in &object.fields {
        push_fmt(output, format_args!("    /// Field `{}` from the source schema.\n", field.name));
        push_fmt(output, format_args!("    pub {}: {},\n", field.name, rust_type(&field.r#type)));
    }
    output.push_str("}\n");
}

pub(super) fn render_typescript(
    schema: &WesleyIR,
    schema_hash: &str,
    schema_path: &Path,
) -> Result<String, Box<dyn std::error::Error>> {
    let mut output = String::new();
    output.push_str("// @generated by bunny-wesley. Do not edit by hand.\n");
    push_fmt(&mut output, format_args!("// source: {}\n\n", normalize_path(schema_path)));
    push_fmt(
        &mut output,
        format_args!("export const BUNNY_GRAPHICS_SCHEMA_SHA256 = \"{schema_hash}\" as const;\n\n"),
    );
    push_fmt(
        &mut output,
        format_args!("export const BUNNY_WESLEY_GENERATOR = \"{GENERATOR_ID}\" as const;\n"),
    );
    push_fmt(
        &mut output,
        format_args!(
            "export const BUNNY_WESLEY_CORE_VERSION = \"{WESLEY_CORE_VERSION}\" as const;\n\n"
        ),
    );

    push_typescript_scalars(&mut output, schema)?;
    profile::push_typescript_scalar_profiles(&mut output, schema)?;
    push_typescript_objects(&mut output, schema);
    Ok(output)
}

fn push_typescript_scalars(
    output: &mut String,
    schema: &WesleyIR,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut scalars = schema
        .types
        .iter()
        .filter(|type_definition| matches!(type_definition.kind, TypeKind::Scalar))
        .collect::<Vec<_>>();
    scalars.sort_by(|left, right| left.name.cmp(&right.name));
    for scalar in &scalars {
        push_fmt(
            output,
            format_args!("export type {} = {};\n", scalar.name, profile::ts_scalar_type(scalar)?),
        );
    }
    if !scalars.is_empty() {
        output.push('\n');
    }
    Ok(())
}

fn push_typescript_objects(output: &mut String, schema: &WesleyIR) {
    let mut objects = schema
        .types
        .iter()
        .filter(|type_definition| {
            matches!(type_definition.kind, TypeKind::Object) && is_bunny_type(&type_definition.name)
        })
        .collect::<Vec<_>>();
    objects.sort_by(|left, right| left.name.cmp(&right.name));
    for object in objects {
        push_typescript_object(output, object);
    }
}

fn push_typescript_object(output: &mut String, object: &TypeDefinition) {
    push_fmt(output, format_args!("export interface {} {{\n", object.name));
    for field in &object.fields {
        push_fmt(output, format_args!("  readonly {}: {};\n", field.name, ts_type(&field.r#type)));
    }
    output.push_str("}\n\n");
}

pub(crate) fn rust_type(type_reference: &TypeReference) -> String {
    let named = rust_scalar_or_named_type(&type_reference.base);
    let rendered = if type_reference.is_list || !type_reference.list_wrappers.is_empty() {
        let item = if type_reference.list_item_nullable.unwrap_or(false) {
            format!("Option<{named}>")
        } else {
            named
        };
        format!("Vec<{item}>")
    } else {
        named
    };

    if type_reference.nullable {
        format!("Option<{rendered}>")
    } else {
        rendered
    }
}

pub(crate) fn ts_type(type_reference: &TypeReference) -> String {
    let named = ts_scalar_or_named_type(&type_reference.base);
    let rendered = if type_reference.is_list || !type_reference.list_wrappers.is_empty() {
        let item = if type_reference.list_item_nullable.unwrap_or(false) {
            format!("{} | null", ts_wrap_union(named))
        } else {
            named
        };
        format!("{}[]", ts_wrap_union(item))
    } else {
        named
    };

    if type_reference.nullable {
        format!("{} | null", ts_wrap_union(rendered))
    } else {
        rendered
    }
}

fn rust_scalar_or_named_type(name: &str) -> String {
    match name {
        "String" | "ID" => "String".to_string(),
        "Int" => "i32".to_string(),
        "Float" => "f64".to_string(),
        "Boolean" => "bool".to_string(),
        other => other.to_string(),
    }
}

fn ts_scalar_or_named_type(name: &str) -> String {
    match name {
        "String" | "ID" => "string".to_string(),
        "Int" | "Float" => "number".to_string(),
        "Boolean" => "boolean".to_string(),
        other => other.to_string(),
    }
}

fn is_bunny_type(name: &str) -> bool {
    name.starts_with(BUNNY_TYPE_PREFIX)
}

fn ts_wrap_union(rendered_type: String) -> String {
    if rendered_type.contains(" | ") {
        format!("({rendered_type})")
    } else {
        rendered_type
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_nullable_scalar_and_non_null_list() {
        let nullable_scalar = TypeReference {
            base: "TestScalar".to_string(),
            nullable: true,
            is_list: false,
            list_item_nullable: None,
            list_wrappers: Vec::new(),
            leaf_nullable: None,
        };
        let point_list = TypeReference {
            base: "BunnyContactPoint3".to_string(),
            nullable: false,
            is_list: true,
            list_item_nullable: Some(false),
            list_wrappers: Vec::new(),
            leaf_nullable: None,
        };

        assert_eq!(rust_type(&nullable_scalar), "Option<TestScalar>");
        assert_eq!(ts_type(&nullable_scalar), "TestScalar | null");
        assert_eq!(rust_type(&point_list), "Vec<BunnyContactPoint3>");
        assert_eq!(ts_type(&point_list), "BunnyContactPoint3[]");
    }

    #[test]
    fn test_lower_schema_sdl_preserves_type_order() {
        let schema = r"
type First {
  value: String!
}

type Second {
  value: Int
}
";

        let objects = wesley_core::lower_schema_sdl(schema).expect("schema parses").types;

        assert_eq!(objects[0].name, "First");
        assert_eq!(objects[1].name, "Second");
        assert_eq!(rust_type(&objects[1].fields[0].r#type), "Option<i32>");
    }

    #[test]
    fn test_directive_scalar_mapping() {
        let schema = r#"
            directive @bunnyScalarProfile(name: String!) on SCALAR
            scalar TestScalar1 @bunnyScalarProfile(name: "f32")
            scalar TestScalar2 @bunnyScalarProfile(name: "q32.32")
            scalar CustomScalar @bunnyScalarProfile(name: "q32.32")
        "#;
        let ir = wesley_core::lower_schema_sdl(schema).unwrap();

        let float_scalar = ir.types.iter().find(|t| t.name == "TestScalar1").unwrap();
        let fixed_scalar = ir.types.iter().find(|t| t.name == "TestScalar2").unwrap();
        let custom_scalar = ir.types.iter().find(|t| t.name == "CustomScalar").unwrap();

        assert_eq!(profile::rust_scalar_type(float_scalar).unwrap(), "f32");
        assert_eq!(profile::ts_scalar_type(float_scalar).unwrap(), "number");

        assert_eq!(profile::rust_scalar_type(fixed_scalar).unwrap(), "i64");
        assert_eq!(profile::ts_scalar_type(fixed_scalar).unwrap(), "bigint");

        assert_eq!(profile::rust_scalar_type(custom_scalar).unwrap(), "i64");
        assert_eq!(profile::ts_scalar_type(custom_scalar).unwrap(), "bigint");
    }

    #[test]
    fn render_rejects_custom_scalars_without_profiles() {
        let schema = r"
            scalar ExternalId

            type BunnyThing {
              id: ExternalId!
            }
        ";
        let ir = wesley_core::lower_schema_sdl(schema).unwrap();

        let rust_error = render_rust(&ir, "hash", Path::new("schema.graphql")).unwrap_err();
        assert!(rust_error
            .to_string()
            .contains("Missing `@bunnyScalarProfile` directive on scalar 'ExternalId'"));

        let ts_error = render_typescript(&ir, "hash", Path::new("schema.graphql")).unwrap_err();
        assert!(ts_error
            .to_string()
            .contains("Missing `@bunnyScalarProfile` directive on scalar 'ExternalId'"));
    }

    #[test]
    fn test_invalid_directive_profile_errors() {
        let schema = r#"
            directive @bunnyScalarProfile(name: String!) on SCALAR
            scalar TestInvalid @bunnyScalarProfile(name: "f64")
        "#;
        let ir = wesley_core::lower_schema_sdl(schema).unwrap();
        let scalar_invalid = ir.types.iter().find(|t| t.name == "TestInvalid").unwrap();

        assert!(profile::rust_scalar_type(scalar_invalid).is_err());
        assert!(profile::ts_scalar_type(scalar_invalid).is_err());
    }
}
