use std::path::Path;
use wesley_core::{TypeDefinition, TypeKind, TypeReference, WesleyIR};

pub const GENERATOR_ID: &str = concat!("bunny-wesley/", env!("CARGO_PKG_VERSION"));
pub const WESLEY_CORE_VERSION: &str = env!("WESLEY_CORE_VERSION");

const BUNNY_TYPE_PREFIX: &str = "Bunny";
const SCALAR_PROFILE_DIRECTIVE: &str = "bunnyScalarProfile";
const SCALAR_PROFILE_NAME_ARGUMENT: &str = "name";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct ScalarProfile {
    name: &'static str,
    rust_type: &'static str,
    typescript_type: &'static str,
}

const SCALAR_PROFILES: &[ScalarProfile] = &[
    ScalarProfile {
        name: "f32",
        rust_type: "f32",
        typescript_type: "number",
    },
    ScalarProfile {
        name: "q32.32",
        rust_type: "i64",
        typescript_type: "bigint",
    },
];

fn normalize_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

pub fn render_rust(
    schema: &WesleyIR,
    schema_hash: &str,
    schema_path: &Path,
) -> Result<String, Box<dyn std::error::Error>> {
    let mut output = String::new();
    output.push_str("// @generated by bunny-wesley. Do not edit by hand.\n");
    output.push_str(&format!("// source: {}\n\n", normalize_path(schema_path)));
    output.push_str("pub const BUNNY_GRAPHICS_SCHEMA_SHA256: &str =\n");
    output.push_str(&format!("    \"{schema_hash}\";\n\n"));
    output.push_str(&format!(
        "pub const BUNNY_WESLEY_GENERATOR: &str = \"{GENERATOR_ID}\";\n"
    ));
    output.push_str(&format!(
        "pub const BUNNY_WESLEY_CORE_VERSION: &str = \"{WESLEY_CORE_VERSION}\";\n\n"
    ));

    for scalar in schema
        .types
        .iter()
        .filter(|type_definition| matches!(type_definition.kind, TypeKind::Scalar))
    {
        if scalar.name.contains('_') {
            output.push_str("#[allow(non_camel_case_types)]\n");
        }
        output.push_str(&format!(
            "pub type {} = {};\n",
            scalar.name,
            rust_scalar_type(scalar)?
        ));
    }
    if schema
        .types
        .iter()
        .any(|type_definition| matches!(type_definition.kind, TypeKind::Scalar))
    {
        output.push('\n');
    }

    let objects: Vec<_> = schema
        .types
        .iter()
        .filter(|type_definition| {
            matches!(type_definition.kind, TypeKind::Object) && is_bunny_type(&type_definition.name)
        })
        .collect();

    for (index, object) in objects.iter().enumerate() {
        output.push_str("#[derive(Clone, Debug, PartialEq)]\n");
        output.push_str(&format!("pub struct {} {{\n", object.name));
        for field in &object.fields {
            output.push_str(&format!(
                "    pub {}: {},\n",
                field.name,
                rust_type(&field.r#type)
            ));
        }
        output.push_str("}\n");
        if index + 1 < objects.len() {
            output.push('\n');
        }
    }

    Ok(output)
}

pub fn render_typescript(
    schema: &WesleyIR,
    schema_hash: &str,
    schema_path: &Path,
) -> Result<String, Box<dyn std::error::Error>> {
    let mut output = String::new();
    output.push_str("// @generated by bunny-wesley. Do not edit by hand.\n");
    output.push_str(&format!("// source: {}\n\n", normalize_path(schema_path)));
    output.push_str(&format!(
        "export const BUNNY_GRAPHICS_SCHEMA_SHA256 = \"{schema_hash}\" as const;\n\n"
    ));
    output.push_str(&format!(
        "export const BUNNY_WESLEY_GENERATOR = \"{GENERATOR_ID}\" as const;\n"
    ));
    output.push_str(&format!(
        "export const BUNNY_WESLEY_CORE_VERSION = \"{WESLEY_CORE_VERSION}\" as const;\n\n"
    ));

    for scalar in schema
        .types
        .iter()
        .filter(|type_definition| matches!(type_definition.kind, TypeKind::Scalar))
    {
        output.push_str(&format!(
            "export type {} = {};\n",
            scalar.name,
            ts_scalar_type(scalar)?
        ));
    }
    if schema
        .types
        .iter()
        .any(|type_definition| matches!(type_definition.kind, TypeKind::Scalar))
    {
        output.push('\n');
    }

    for object in schema.types.iter().filter(|type_definition| {
        matches!(type_definition.kind, TypeKind::Object) && is_bunny_type(&type_definition.name)
    }) {
        output.push_str(&format!("export interface {} {{\n", object.name));
        for field in &object.fields {
            output.push_str(&format!(
                "  readonly {}: {};\n",
                field.name,
                ts_type(&field.r#type)
            ));
        }
        output.push_str("}\n\n");
    }

    Ok(output)
}

pub(crate) fn rust_type(type_reference: &TypeReference) -> String {
    let named = rust_scalar_or_named_type(&type_reference.base);
    let rendered = if type_reference.is_list || !type_reference.list_wrappers.is_empty() {
        let item = if type_reference.list_item_nullable.unwrap_or(false) {
            format!("Option<{named}>")
        } else {
            named
        };
        format!("Vec<{item}>")
    } else {
        named
    };

    if type_reference.nullable {
        format!("Option<{rendered}>")
    } else {
        rendered
    }
}

pub(crate) fn ts_type(type_reference: &TypeReference) -> String {
    let named = ts_scalar_or_named_type(&type_reference.base);
    let rendered = if type_reference.is_list || !type_reference.list_wrappers.is_empty() {
        let item = if type_reference.list_item_nullable.unwrap_or(false) {
            format!("{} | null", ts_wrap_union(named))
        } else {
            named
        };
        format!("{}[]", ts_wrap_union(item))
    } else {
        named
    };

    if type_reference.nullable {
        format!("{} | null", ts_wrap_union(rendered))
    } else {
        rendered
    }
}

fn rust_scalar_or_named_type(name: &str) -> String {
    match name {
        "String" | "ID" => "String".to_string(),
        "Int" => "i32".to_string(),
        "Float" => "f64".to_string(),
        "Boolean" => "bool".to_string(),
        other => other.to_string(),
    }
}

fn scalar_profile_by_name(name: &str) -> Option<&'static ScalarProfile> {
    SCALAR_PROFILES.iter().find(|profile| profile.name == name)
}

fn resolve_profile(scalar_def: &TypeDefinition) -> Result<&'static ScalarProfile, String> {
    let profile_val = scalar_def
        .directives
        .get(SCALAR_PROFILE_DIRECTIVE)
        .ok_or_else(|| {
            format!(
                "Missing `@bunnyScalarProfile` directive on scalar '{}'",
                scalar_def.name
            )
        })?;
    let obj = profile_val.as_object().ok_or_else(|| {
        format!(
            "`@bunnyScalarProfile` directive on scalar '{}' must be an object with arguments",
            scalar_def.name
        )
    })?;
    let name_val = obj
        .get(SCALAR_PROFILE_NAME_ARGUMENT)
        .ok_or_else(|| {
            format!(
                "Missing 'name' argument in `@bunnyScalarProfile` on scalar '{}'",
                scalar_def.name
            )
        })?
        .as_str()
        .ok_or_else(|| {
            format!(
                "'name' argument in `@bunnyScalarProfile` on scalar '{}' must be a string",
                scalar_def.name
            )
        })?;

    scalar_profile_by_name(name_val).ok_or_else(|| {
        format!(
            "Unsupported scalar profile '{}' on scalar '{}'",
            name_val, scalar_def.name
        )
    })
}

pub fn rust_scalar_type(scalar_def: &TypeDefinition) -> Result<&'static str, String> {
    Ok(resolve_profile(scalar_def)?.rust_type)
}

fn ts_scalar_or_named_type(name: &str) -> String {
    match name {
        "String" | "ID" => "string".to_string(),
        "Int" | "Float" => "number".to_string(),
        "Boolean" => "boolean".to_string(),
        other => other.to_string(),
    }
}

pub fn ts_scalar_type(scalar_def: &TypeDefinition) -> Result<&'static str, String> {
    Ok(resolve_profile(scalar_def)?.typescript_type)
}

fn is_bunny_type(name: &str) -> bool {
    name.starts_with(BUNNY_TYPE_PREFIX)
}

fn ts_wrap_union(rendered_type: String) -> String {
    if rendered_type.contains(" | ") {
        format!("({rendered_type})")
    } else {
        rendered_type
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_nullable_scalar_and_non_null_list() {
        let nullable_scalar = TypeReference {
            base: "TestScalar".to_string(),
            nullable: true,
            is_list: false,
            list_item_nullable: None,
            list_wrappers: Vec::new(),
            leaf_nullable: None,
        };
        let point_list = TypeReference {
            base: "BunnyContactPoint3".to_string(),
            nullable: false,
            is_list: true,
            list_item_nullable: Some(false),
            list_wrappers: Vec::new(),
            leaf_nullable: None,
        };

        assert_eq!(rust_type(&nullable_scalar), "Option<TestScalar>");
        assert_eq!(ts_type(&nullable_scalar), "TestScalar | null");
        assert_eq!(rust_type(&point_list), "Vec<BunnyContactPoint3>");
        assert_eq!(ts_type(&point_list), "BunnyContactPoint3[]");
    }

    #[test]
    fn test_lower_schema_sdl_preserves_type_order() {
        let schema = r#"
type First {
  value: String!
}

type Second {
  value: Int
}
"#;

        let objects = wesley_core::lower_schema_sdl(schema)
            .expect("schema parses")
            .types;

        assert_eq!(objects[0].name, "First");
        assert_eq!(objects[1].name, "Second");
        assert_eq!(rust_type(&objects[1].fields[0].r#type), "Option<i32>");
    }

    #[test]
    fn test_directive_scalar_mapping() {
        let schema = r#"
            directive @bunnyScalarProfile(name: String!) on SCALAR
            scalar TestScalar1 @bunnyScalarProfile(name: "f32")
            scalar TestScalar2 @bunnyScalarProfile(name: "q32.32")
            scalar CustomScalar @bunnyScalarProfile(name: "q32.32")
        "#;
        let ir = wesley_core::lower_schema_sdl(schema).unwrap();

        let scalar_f32 = ir.types.iter().find(|t| t.name == "TestScalar1").unwrap();
        let scalar_q32 = ir.types.iter().find(|t| t.name == "TestScalar2").unwrap();
        let scalar_custom = ir.types.iter().find(|t| t.name == "CustomScalar").unwrap();

        assert_eq!(rust_scalar_type(scalar_f32).unwrap(), "f32");
        assert_eq!(ts_scalar_type(scalar_f32).unwrap(), "number");

        assert_eq!(rust_scalar_type(scalar_q32).unwrap(), "i64");
        assert_eq!(ts_scalar_type(scalar_q32).unwrap(), "bigint");

        assert_eq!(rust_scalar_type(scalar_custom).unwrap(), "i64");
        assert_eq!(ts_scalar_type(scalar_custom).unwrap(), "bigint");
    }

    #[test]
    fn render_rejects_custom_scalars_without_profiles() {
        let schema = r#"
            scalar ExternalId

            type BunnyThing {
              id: ExternalId!
            }
        "#;
        let ir = wesley_core::lower_schema_sdl(schema).unwrap();

        let rust_error = render_rust(&ir, "hash", Path::new("schema.graphql")).unwrap_err();
        assert!(rust_error
            .to_string()
            .contains("Missing `@bunnyScalarProfile` directive on scalar 'ExternalId'"));

        let ts_error = render_typescript(&ir, "hash", Path::new("schema.graphql")).unwrap_err();
        assert!(ts_error
            .to_string()
            .contains("Missing `@bunnyScalarProfile` directive on scalar 'ExternalId'"));
    }

    #[test]
    fn scalar_profiles_are_registry_driven() {
        assert_eq!(scalar_profile_by_name("f32").unwrap().rust_type, "f32");
        assert_eq!(
            scalar_profile_by_name("q32.32").unwrap().typescript_type,
            "bigint"
        );

        let source = include_str!("render.rs");
        let legacy_float_name = ["Bunny", "Scalar"].concat();
        let legacy_fixed_name = ["Bunny", "FixedQ32_32Raw"].concat();
        let branch_pattern = ["match", " name", "_val"].concat();

        assert!(!source.contains(&legacy_float_name));
        assert!(!source.contains(&legacy_fixed_name));
        assert!(!source.contains(&branch_pattern));
    }

    #[test]
    fn test_invalid_directive_profile_errors() {
        let schema = r#"
            directive @bunnyScalarProfile(name: String!) on SCALAR
            scalar TestInvalid @bunnyScalarProfile(name: "f64")
        "#;
        let ir = wesley_core::lower_schema_sdl(schema).unwrap();
        let scalar_invalid = ir.types.iter().find(|t| t.name == "TestInvalid").unwrap();

        assert!(rust_scalar_type(scalar_invalid).is_err());
        assert!(ts_scalar_type(scalar_invalid).is_err());
    }
}
