use std::path::Path;
use wesley_core::{TypeDefinition, TypeKind, TypeReference, WesleyIR};

const GENERATOR_ID: &str = "bunny-wesley/0.1.0";
const WESLEY_CORE_VERSION: &str = "0.0.5";

pub fn render_rust(schema: &WesleyIR, schema_hash: &str, schema_path: &Path) -> String {
    let mut output = String::new();
    output.push_str("// @generated by bunny-wesley. Do not edit by hand.\n");
    output.push_str(&format!("// source: {}\n\n", schema_path.display()));
    output.push_str("pub const BUNNY_GRAPHICS_SCHEMA_SHA256: &str =\n");
    output.push_str(&format!("    \"{schema_hash}\";\n\n"));
    output.push_str(&format!(
        "pub const BUNNY_WESLEY_GENERATOR: &str = \"{GENERATOR_ID}\";\n"
    ));
    output.push_str(&format!(
        "pub const BUNNY_WESLEY_CORE_VERSION: &str = \"{WESLEY_CORE_VERSION}\";\n\n"
    ));

    for scalar in schema.types.iter().filter(|type_definition| {
        matches!(type_definition.kind, TypeKind::Scalar) && is_bunny_type(&type_definition.name)
    }) {
        if scalar.name.contains('_') {
            output.push_str("#[allow(non_camel_case_types)]\n");
        }
        output.push_str(&format!(
            "pub type {} = {};\n",
            scalar.name,
            rust_scalar_type(scalar)
        ));
    }
    if schema
        .types
        .iter()
        .any(|type_definition| matches!(type_definition.kind, TypeKind::Scalar))
    {
        output.push('\n');
    }

    let objects: Vec<_> = schema
        .types
        .iter()
        .filter(|type_definition| {
            matches!(type_definition.kind, TypeKind::Object) && is_bunny_type(&type_definition.name)
        })
        .collect();

    for (index, object) in objects.iter().enumerate() {
        output.push_str("#[derive(Clone, Debug, PartialEq)]\n");
        output.push_str(&format!("pub struct {} {{\n", object.name));
        for field in &object.fields {
            output.push_str(&format!(
                "    pub {}: {},\n",
                field.name,
                rust_type(&field.r#type)
            ));
        }
        output.push_str("}\n");
        if index + 1 < objects.len() {
            output.push('\n');
        }
    }

    output
}

pub fn render_typescript(schema: &WesleyIR, schema_hash: &str, schema_path: &Path) -> String {
    let mut output = String::new();
    output.push_str("// @generated by bunny-wesley. Do not edit by hand.\n");
    output.push_str(&format!("// source: {}\n\n", schema_path.display()));
    output.push_str(&format!(
        "export const BUNNY_GRAPHICS_SCHEMA_SHA256 = \"{schema_hash}\" as const;\n\n"
    ));
    output.push_str(&format!(
        "export const BUNNY_WESLEY_GENERATOR = \"{GENERATOR_ID}\" as const;\n"
    ));
    output.push_str(&format!(
        "export const BUNNY_WESLEY_CORE_VERSION = \"{WESLEY_CORE_VERSION}\" as const;\n\n"
    ));

    for scalar in schema.types.iter().filter(|type_definition| {
        matches!(type_definition.kind, TypeKind::Scalar) && is_bunny_type(&type_definition.name)
    }) {
        output.push_str(&format!(
            "export type {} = {};\n",
            scalar.name,
            ts_scalar_type(scalar)
        ));
    }
    if schema
        .types
        .iter()
        .any(|type_definition| matches!(type_definition.kind, TypeKind::Scalar))
    {
        output.push('\n');
    }

    for object in schema.types.iter().filter(|type_definition| {
        matches!(type_definition.kind, TypeKind::Object) && is_bunny_type(&type_definition.name)
    }) {
        output.push_str(&format!("export interface {} {{\n", object.name));
        for field in &object.fields {
            output.push_str(&format!(
                "  readonly {}: {};\n",
                field.name,
                ts_type(&field.r#type)
            ));
        }
        output.push_str("}\n\n");
    }

    output
}

pub(crate) fn rust_type(type_reference: &TypeReference) -> String {
    let named = rust_scalar_or_named_type(&type_reference.base);
    let rendered = if type_reference.is_list || !type_reference.list_wrappers.is_empty() {
        let item = if type_reference.list_item_nullable.unwrap_or(false) {
            format!("Option<{named}>")
        } else {
            named
        };
        format!("Vec<{item}>")
    } else {
        named
    };

    if type_reference.nullable {
        format!("Option<{rendered}>")
    } else {
        rendered
    }
}

pub(crate) fn ts_type(type_reference: &TypeReference) -> String {
    let named = ts_scalar_or_named_type(&type_reference.base);
    let rendered = if type_reference.is_list || !type_reference.list_wrappers.is_empty() {
        let item = if type_reference.list_item_nullable.unwrap_or(false) {
            format!("{} | null", ts_wrap_union(named))
        } else {
            named
        };
        format!("{}[]", ts_wrap_union(item))
    } else {
        named
    };

    if type_reference.nullable {
        format!("{} | null", ts_wrap_union(rendered))
    } else {
        rendered
    }
}

fn rust_scalar_or_named_type(name: &str) -> String {
    match name {
        "String" | "ID" => "String".to_string(),
        "Int" => "i32".to_string(),
        "Float" => "f64".to_string(),
        "Boolean" => "bool".to_string(),
        other => other.to_string(),
    }
}

fn resolve_profile_types(scalar_def: &TypeDefinition) -> (&'static str, &'static str) {
    if let Some(profile_val) = scalar_def.directives.get("bunnyScalarProfile") {
        if let Some(obj) = profile_val.as_object() {
            if let Some(name_val) = obj.get("name") {
                if let Some(profile_name) = name_val.as_str() {
                    match profile_name {
                        "f32" => return ("f32", "number"),
                        "q32.32" => return ("i64", "bigint"),
                        _ => {}
                    }
                }
            }
        }
    }
    ("String", "unknown")
}

pub fn rust_scalar_type(scalar_def: &TypeDefinition) -> &'static str {
    resolve_profile_types(scalar_def).0
}

fn ts_scalar_or_named_type(name: &str) -> String {
    match name {
        "String" | "ID" => "string".to_string(),
        "Int" | "Float" => "number".to_string(),
        "Boolean" => "boolean".to_string(),
        other => other.to_string(),
    }
}

pub fn ts_scalar_type(scalar_def: &TypeDefinition) -> &'static str {
    resolve_profile_types(scalar_def).1
}

fn is_bunny_type(name: &str) -> bool {
    name.starts_with("Bunny")
}

fn ts_wrap_union(rendered_type: String) -> String {
    if rendered_type.contains(" | ") {
        format!("({rendered_type})")
    } else {
        rendered_type
    }
}
